apiVersion: apps/v1
kind: Deployment
metadata:
  name: exercises-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exerciseservice
  template:
    metadata:
      labels:
        app: exerciseservice
    spec:
      containers:
      - name: exerciseservice
        image: irchubarkina/exerciseservice
