apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec: 
  rules:
    - host: irina.com
      http:
        paths:
          - path: /api/exercises
            pathType: Prefix
            backend: 
              service: 
                name: exercises-clusterip-srv
                port: 
                  number: 80
          - path: /api/tr/exercises
            pathType: Prefix
            backend: 
              service: 
                name: training-programs-clusterip-srv
                port: 
                  number: 80
